/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.13/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    java
    application
}

group = "xknr.millerrabin"
version = "1.0.0"


repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)
    implementation("xknr.euler:eulerutil:1.0.0")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "org.example.App"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

tasks.test {
    jvmArgs = listOf("-Xmx2g")  // Set max heap size to 2GB (you can increase/decrease as needed)

    testLogging {
        events("passed", "skipped", "failed", "standardOut", "standardError")
        showStandardStreams = true
    }
}

tasks.register<JavaExec>("runExhaustiveMRTest") {
    group = "application"
    description = "Run exhaustive test for miller rabin code"
    classpath = sourceSets["main"].runtimeClasspath
    mainClass.set("xknr.millerrabin.MillerRabinExhaustive")
}



tasks.register<JavaExec>("runBench") {
    group = "application"
    description = "Run benchmarks miller rabin code"
    classpath = sourceSets["main"].runtimeClasspath
    mainClass.set("xknr.millerrabin.Benchmark")
}

sourceSets["main"].java.srcDirs(
    "libs/eulerutil/src/main/java",
    "libs/int128/src/main/java"
)
 

sourceSets["test"].java.srcDirs(
    "libs/eulerutil/src/test/java"
)

